language: python
python:
  - "3.6"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
  - DJANGO=3.2
install:
  - pip install --timeout=30 -q Django==$DJANGO
  - pip install --timeout=30 pep8
  - pip install --timeout=30 pyflakes
  - pip install --timeout=30 -r requirements.txt
  - pip install --timeout=30 -q -e .
before_script:
  - make verify
script:
  - make test
notifications:
  slack: smartfile:tbDIPzVJIPBpSz29kQw6b8RQ
