language: python
python:
  - "3.6"
env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
install:
  - pip install --timeout=30 -q Django==$DJANGO
  - pip install --timeout=30 pep8
  - pip install --timeout=30 https://github.com/dcramer/pyflakes/tarball/master
  - pip install --timeout=30 -r requirements.txt
  - pip install --timeout=30 -q -e .
before_script:
  - make verify
script:
  - make test
notifications:
  slack: smartfile:tbDIPzVJIPBpSz29kQw6b8RQ
