name: CI
on: [push, pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        django-version: [ '2.0', '2.1', '2.2', '3.0', '3.1', '3.2' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --timeout=30 -q Django==${{ matrix.django-version }}
          pip install --timeout=30 pep8
          pip install --timeout=30 pyflakes
          pip install --timeout=30 -r requirements.txt
          pip install --timeout=30 -q -e .

      - name: Run linter
        run: make verify

      - name: Run unit tests
        run: make test
